openstack-k8s-operators/mariadb-operator

controllers/mariadbdatabase_controller.go
pkg/database.go
templates/delete_database.sh

Introduces a finalizer to run a DB delete job on CR delete to be
able to cleanup also DB from other operators.

Use finalizer to cleanup DB on CR delete

---

pkg/database.go

This is not a full polished patch, just removes the invalid
underscore character from the metadata name.

Allow underscore in db names like nova_api, nova_cell0

---

controllers/mariadbdatabase_controller.go
controllers/suite_test.go

This resolves a race introduced in 5d6e4248 where MariaDBDatabase
objects might not get created unless the MariaDB already exists.
The issue was that reconcile was returning a nil result (thus
signalling completion) when it was supposed to be blocking
on the MariaDB to be created.

Fix race with MariaDB/MariaDBDatabase

---

config/rbac/role.yaml
controllers/mariadbdatabase_controller.go

The controller right now does not have permissiones to
set the finalizer:
~~~
1.6526971536152077e+09  ERROR   controller.mariadbdatabase      Reconciler error        {"reconciler group": "mariadb.openstack.org", "reconciler kind": "MariaDBDatabase", "name": "keystoneapi", "namespace": "openstack", "error": "jobs.batch \"keystoneapi-database-sync\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
~~~

Allow update finalizer for mariadbdatabase controller

---

Dockerfile

This change add runAsUser to the
security context to avoid the following error:
container has runAsNonRoot and image has non-numeric user (nonroot),
cannot verify user is non-root

set user in container spec

---

.github/workflows/build-mariadb-operator.yaml
Makefile
api/bases/mariadb.openstack.org_mariadbdatabases.yaml
api/bases/mariadb.openstack.org_mariadbs.yaml
config/crd/bases/mariadb.openstack.org_mariadbdatabases.yaml
config/crd/bases/mariadb.openstack.org_mariadbs.yaml
config/default/manager_auth_proxy_patch.yaml
go.mod
go.sum

Copies the rendered CRD files dir to /api/bases in make manifests when successfully generated.
Also some minor updates for SDK1.23.0

Copy generated CRD files dir to /api/bases

---

pkg/database.go

Rename it from x-database-sync to x-db-create as it is not really calling db sync just creating and empty database named x. Also we are not simply dropping underscores from the name but replacing it with a hyphen to make the names more readable.

Rename the Job used to create the DB

---

config/rbac/role.yaml
controllers/mariadb_controller.go

For adoptionRedirect the operator manages Endpoints resources directly, we need to make sure it has the rights to do so.

Add Endpoints rights to RBAC

---

api/bases/mariadb.openstack.org_mariadbs.yaml
api/v1beta1/mariadb_types.go
config/crd/bases/mariadb.openstack.org_mariadbs.yaml
config/samples/mariadb_v1beta1_mariadb.yaml

This change makes the contianer image optional and defaults
the image to use stable/zed.

use stable/zed images

---

kuttl-test.yaml
tests/kuttl/tests/mariadb_deploy/01-assert.yaml
tests/kuttl/tests/mariadb_deploy/01-deploy-mariadb.yaml

Add a very simple test suite for mariadb that just tests the deployment. This test was extracted from the keystone kuttl test suite and should be expanded in a future change.

Add simple kuttl tests for mariadb

---

controllers/mariadbdatabase_controller.go

Does two things:
1. Adds a self-finalizer to the `MariaDBDatabase` CR.
2. When a `MariaDBDatabase` CR is created, we now add a finalizer to the associated `Galera` or `MariaDB` to prevent accidental deletion of the latter.  We also remove the finalizer from the `Galera` or `MariaDB` when the `MariaDBDatabase` is deleted.

Finalizers for MariaDBDatabase

---

tests/kuttl/common/assert_sample_deployment.yaml

Currently MariaDB kuttl tests check that the database is using
local-storage, but this could potentially change in the future or
between different systems, so we remove this check.

Remove harcoded check for storageClass in Kuttl test

---

.github/workflows/build-mariadb-operator.yaml

We build containers and push to registry in post merge workflow. Not building container for each hash can cause issue becuase of missing container tags. Pin-custom-bundle-dockerfile.sh (openstack-operator) can pin to hash for which images are not available.

Drop paths-ignore from build operator workflow

---

.github/workflows/build-mariadb-operator.yaml

We are hitting rate-limt during post merge image build:
Github rate-limiter failed the request. Either authenticate or wait a couple of minutes.
It seems it is coming from [1] and can be fixed by passing the GITHUB_TOKEN there. So this patch does that to avoid build failures due to rate-limit.
[1] https://github.com/kubernetes-sigs/kustomize/blob/0fd385d7197026b92272dc8688ec66593be91fba/hack/install_kustomize.sh#L145

Pass GITHUB_TOKEN to install_kustomize.sh to avoid rate-limit

---

api/bases/mariadb.openstack.org_galeras.yaml
api/v1beta1/galera_types.go
config/crd/bases/mariadb.openstack.org_galeras.yaml
config/samples/mariadb_v1beta1_galera_custom_config.yaml
controllers/galera_controller.go
pkg/statefulset.go
templates/galera/bin/mysql_bootstrap.sh
templates/galera/config/config.json

This allows a Galera CR to override or pass new configuration variables for the MariaDB server or the CLI. A new field CustomServiceConfig contains raw MariaDB config statements, which are ultimately stored in /etc/my.cnf.d/galera_custom.cnf and processed after the usual galera.cnf.
Updating CustomServiceConfig triggers a rolling restart of the galera pods, without service disruption.

galera: Support additional custom config file

---

templates/galera/config/config.json

Since [1] the kolla config incorrectly sets permissions of the mysql config directory to be accessible by root only. Fix read access for all users, and align the permissions on the config files as well.
[1] 751b510968ab82fe5dd61b2198fb5cd30df0427e

galera: fix permissions of config files

---

Makefile

Add the ability to override health and metrics port to run locally when the environment ports are conflicting with defaults.
Fix the run entry to disable webhooks by default.

Improve makefile run targets

---

api/bases/mariadb.openstack.org_galeras.yaml
api/v1beta1/galera_types.go
config/crd/bases/mariadb.openstack.org_galeras.yaml
controllers/galera_controller.go

The mariadb operator determines whether a starting pod will bootstrap a galera cluster or join an existing one. On startup, the galera pod receives that information via a temporary file injected by the operator. Once galera is running in the pod, the operator updates its status.
Improve the status tracking so that the operator can detect when a pod failed to start galera, and try again in a subsequent reconcile loop.
Also make sure that the operator cannot inspect the galera state while the galera server is being started, to prevent any corruption.

galera: improve recovery of pods

---

.golangci.yaml
.pre-commit-config.yaml
Makefile
controllers/galera_controller.go
controllers/mariadb_controller.go
hack/configure_local_webhook.sh
templates/galera/bin/mysql_bootstrap.sh

This PR replace deprecated go-linter using
revive (https://golangci-lint.run/usage/linters/#revive).
We will add "ginkgolinter" in follow up patch once we merged add pre-commit job in openshift/releases.
If we add "ginkgolinter" in this patch then it's causes below issue [1]
```
level=info msg="[config_reader] Config search paths: [./ /home/prow/go/src/github.com/openstack-k8s-operators/dataplane-operator /home/prow/go/src/github.com/openstack-k8s-operators /home/prow/go/src/github.com /home/prow/go/src /home/prow/go /home/prow /home /]"
level=info msg="[config_reader] Used config file .golangci.yaml"
level=error msg="Running error: unknown linters: 'ginkgolinter', run 'golangci-lint help linters' to see the list of supported linters"
```
This patch also Remove fmt dependency from make …

Add revive to golanci

---

pkg/statefulset.go
templates/galera/bin/mysql_bootstrap.sh
templates/galera/bin/mysql_probe.sh

The galera pods are configured to run as root so that Kolla can copy config files and bootstrap a database. Later, mysqld drops privileges by switching to user mysql via setuid().
Do not explicitely require the root user and use sudo rights instead. This works because Kolla is already allowed to sudo, and the mysqld server can set limits (e.g. file descriptors, sockets) without requiring root privileges.

galera: do not require root user to init/run pods

---

tests/kuttl/tests/mariadb_deploy/01-deploy-mariadb.yaml
tests/kuttl/tests/mariadb_deploy/02-cleanup-mariadb.yaml
tests/kuttl/tests/mariadb_deploy/02-errors.yaml
tests/kuttl/tests/mariadb_deploy/deploy/kustomization.yaml

Instead of using install_yamls targets for deploying and cleaning up
mariadb, use the CR sample from config/samples. This removes a possible
circular dependency issue when using install_yamls to run the jobs and
to run some test steps.

Remove install_yamls dependency for kuttl tests

---

Makefile
config/default/manager_default_images.yaml
config/samples/mariadb_v1beta1_galera.yaml
config/samples/mariadb_v1beta1_galera_custom_config.yaml
config/samples/mariadb_v1beta1_mariadb.yaml
tests/kuttl/common/assert_sample_deployment.yaml

We imported container build tools from TripleO as TCIB[1]. Now we are retiring TripleO and should complete the migration.
[1] https://github.com/openstack-k8s-operators/tcib

Replace TripleO images by TCIB images

---

config/rbac/role.yaml
controllers/mariadb_controller.go

The mariadb controller should be able to patch pods, for example when the mariadb service container image is updated. This fixes the missing rbac.

Allow mariadb controller to patch pods

---

kuttl-test.yaml
tests/kuttl/common/assert_sample_deployment.yaml
tests/kuttl/common/create_secret.yaml
tests/kuttl/tests/galera_deploy/00-create-secret.yaml
tests/kuttl/tests/galera_deploy/01-assert.yaml
tests/kuttl/tests/galera_deploy/01-deploy_galera.yaml
tests/kuttl/tests/galera_deploy/02-scale_down_galera.yaml
tests/kuttl/tests/galera_deploy/03-cleanup_galera.yaml
tests/kuttl/tests/galera_deploy/03-errors.yaml
tests/kuttl/tests/mariadb_deploy/00-create-secret.yaml
tests/kuttl/tests/mariadb_deploy/01-deploy-mariadb.yaml
tests/kuttl/tests/mariadb_deploy/02-cleanup-mariadb.yaml

After recent changes in dynamic service account, since mariadb can be
deployed in any namespace, this change modifies the way the kuttl tests
are run, so they run in a namespace automatically created (and deleted) by
kuttl. This allows us to run the kuttl tests in a cluster where we have
already a deployed instance, without interfering. Additionally, we get
the benefit of being able to run multiple tests in parallel, since each
runs in its own namespace, which also reduces the runtime.

Use automatically generated namespace for kuttl tests

---

controllers/galera_controller.go
controllers/mariadb_controller.go

This ensures the Ready Condition is reset when CR becomes once ready but something fails during reconfiguration.

Reset Ready condition when update failed

---

renovate.json

This pins k8s and controller runtime to be in sync with lib-common and configure renovate to keep the pin

Configure renovate to pin k8s and controller-runtime for dev preview

---

controllers/galera_controller.go
controllers/mariadb_controller.go

This ensures the controller watches service account, role, and role bindings to reconcile these resources in case any change is made.

Watch RBAC resources to trigger reconcile

---

api/go.mod
api/go.sum
go.mod
go.sum

Depends-on: https://github.com/openstack-k8s-operators/mariadb-operator/pull/127 (merged)

Bump lib common to v0.1.0

---

.github/create_bundle.sh
.prow_ci.env
api/v1beta1/mariadb_types.go
config/default/manager_default_images.yaml
config/manifests/bases/mariadb-operator.clusterserviceversion.yaml
tests/kuttl/common/assert_sample_deployment.yaml
tests/kuttl/tests/mariadb_deploy/01-assert.yaml

This PR adds support for installing the operator in disconnected network environments. To build with image-digests set USE_IMAGE_DIGESTS=true before running make bundle.
For Prow jobs we are enabling this via .prow-ci.env
This drops the old logic from create_bundle.sh which has been broken with operator-sdk's make bundle for some time.
(NOTE: this currently requires a secure registry)

Support disconnected network environments

---

config/manifests/bases/mariadb-operator.clusterserviceversion.yaml

Update to use new 'features.operators.openshift.io' annotations format for disconnected support
Jira: [OSP-30201](https://issues.redhat.com//browse/OSP-30201)

required infra annotations for OCP 4.14+

---

config/samples/kustomization.yaml

Resolves:
WARN[0000] Warning: Value mariadb.openstack.org/v1beta1, Kind=Galera: provided API should have an example annotation

fix bundle validate: Add Galera to config/samples

---

controllers/galera_controller.go
controllers/mariadb_controller.go
controllers/mariadbdatabase_controller.go
main.go

This automatically adds additional fields like reconcile_id etc.. from the controller context.
before :
`2023-05-18T01:53:14+03:00 INFO  controllers.KeystoneAPI Reconciled Service init successfully`
after:
`2023-10-19T10:38:14+03:00       INFO    Controllers.galera      StatefulSet openstack-cell1-galera - updated    {"controller": "galera", "controllerGroup": "mariadb.openstack.org", "controllerKind": "Galera", "Galera": {"name":"openstack-cell1","namespace":"openstack"}, "namespace": "openstack", "name": "openstack-cell1", "reconcileID": "ceb646eb-6400-460a-a49a-a75b8c821abc"}
`
*by using per reconcile function respective logger objects, the intention is to lay the ground for parallel reconciliation in future and avoid race conditions as ctx objects are reconcile run specific.

switch to structured logging

---

Makefile

specify version for operator-sdk for make bundle
download operator-sdk pinned version when generating bundle update make bundle to use local operator-sdk

update operator-sdk to local-bin

---

templates/galera/bin/mysql_bootstrap.sh

on a dual-stack host (or an ipv6 only host), detect the ipv6 and ipv4 addresses individually from /etc/hosts and apply '[::]' as the gmcast_listen address if ipv6 is present.
Fixes: https://issues.redhat.com/browse/OSPRH-3330

detect ipv6 stack and apply correct listen address

---

api/v1beta1/mariadbdatabase_funcs.go

The Database{} facade that is now used to generate a MariaDBDatabase as well as a MariaDBAccount is currently generating a metadata name for the MariaDBAccount based on the username.  As we do in other places, if this username has underscores in it as is common, swap them out with dashes.

when generating metadata.name, use dashes instead of underscores

---

api/v1beta1/mariadbdatabase_funcs.go

the d.account field is known to be nil here, so logforobject will crash on that.  use a plain info log

dont use logForObject with nil pointer

---

api/test/helpers/crd.go

sumulates database completed for a mariadbdatabase where Status.TLSSupport = true
Jira: [OSPRH-4547](https://issues.redhat.com//browse/OSPRH-4547)

Add SimulateMariaDBTLSDatabaseCompleted helper

---

api/test/helpers/crd.go

Add func to create MariaDBDatabase and MariaDBAccount resources for envtest usage.
related to Jira: [OSPRH-4547](https://issues.redhat.com//browse/OSPRH-4547)

[helpers] MariaDBDatabase and MariaDBAccount create helpers

---

.prow_ci.env
Dockerfile
Makefile
config/manifests/bases/mariadb-operator.clusterserviceversion.yaml

* Changed the build image to `ubi9/go-toolkit:1.20`
* Changed the base image to `ubi9/minimal`
* Added the default `GO_BUILD_EXTRA_ARGS="-tags strictfipsruntime"`
* Added the `GO_BUILD_EXTRA_ENV_ARGS` build argument to allow custom build arguments at build time. It defaults to `"CGO_ENABLED=1 GO111MODULE=on"`
* Those default parameters have been added to enable FIPS compliance
* Fixed indentation
* Added `DOCKER_BUILD_ARGS` variable in Makefile to pass custom parameters during podman build
* Added export `FAIL_FIPS_CHECK=true` to `prow_ci.env` file.

This change ensures the `mariadb-operator` is built with FIPS compliance

---

api/test/helpers/crd.go
api/test/helpers/harnesses.go
api/v1beta1/conditions.go
api/v1beta1/mariadbaccount_types.go
api/v1beta1/mariadbdatabase_funcs.go
api/v1beta1/mariadbdatabase_types.go
api/v1beta1/zz_generated.deepcopy.go
config/manifests/bases/mariadb-operator.clusterserviceversion.yaml
controllers/mariadbaccount_controller.go
pkg/mariadb/account.go
pkg/mariadb/database.go

these changes are to support a phased approach to getting openstack-operator to generate MariaDBAccounts.   I have an initial demo for glance that uses these functions
the glance PR is at https://github.com/openstack-k8s-operators/glance-operator/pull/426/

add functions to support downstream generation of MariaDBAccounts by operators

---

api/v1beta1/mariadbdatabase_funcs.go
api/v1beta1/mariadbdatabase_types.go

every operator is now updated on the newer functions (octavia is still trying to merge), remove all the old functions and old "legacy" codepaths, as a first pass to making this module a little clearer.

remove now-unused mariadb funcs

---

templates/galera/bin/mysql_bootstrap.sh
templates/galera/config/galera_tls.cnf.in

This patch sets the TLS SSL Cipher based on the OCP FIPS mode.
In non FIPS clusters uses AES128-SHA256
And in FIPS clusters uses ECDHE-RSA-AES256-GCM-SHA384
This is the equivalent of what was being done in TripleO [1] [2]
[1]: https://opendev.org/openstack/tripleo-heat-templates/src/commit/500cdbb7deab8034d8a2e2f84cfb2648b7f8c0a4/deployment/database/mysql-pacemaker-puppet.yaml#L107
[2]: https://opendev.org/openstack/tripleo-heat-templates/src/commit/500cdbb7deab8034d8a2e2f84cfb2648b7f8c0a4/environments/fips.yaml#L12
Jira: #[OSPRH-4669](https://issues.redhat.com//browse/OSPRH-4669)

FIPS support

---

.pre-commit-config.yaml
tests/kuttl/tests/database_create/03-assert.yaml
tests/kuttl/tests/galera_create_user_require_tls/02-assert.yaml

Kuttl only runs the last TestAssert in an assert file and silently
ignores the rest. So this patch combines the TestAsserts into a single
one with multiple commands listed.
Also to further secure against false positives `set -euxo pipefail` is
added to the scripts as well.
Also added a new pre-commit check to avoid this in the future.

[pre-commit][kuttl]Fix false positive asserts

---

api/test/helpers/harnesses.go

In nova we need SimulateDeploymentReplicaReady
call after SimulateMariaDBAccountCompleted(newAccountName) too be able reconcile NovaCr. Changes is needed
because we added observeGeneration into subCrs
and now readines logic depend on generations.

Add method to bump generation in tests

---

controllers/galera_controller.go
pkg/mariadb/const.go
pkg/mariadb/service.go
pkg/mariadb/volumes.go
templates/galera/bin/mysql_wsrep_notify.sh
templates/galera/config/galera.cnf.in

The service created for a Galera cluster always balances traffic to all available Galera replicas, which means the cluster is effectively configured as an A/A service.
In order to limit the burden on clients of supporting A/A semantics, change the way the service is configured to act as A/P instead.
A new callback script is introduced in pods. It is called by mysqld automatically every time the Galera library detects a change in the cluster (node join, crash, network partition...). This callback script reconfigures the service CR via label selectors to drive traffic to a single pod at a time.
Jira: [OSPRH-7405](https://issues.redhat.com//browse/OSPRH-7405)

Make Galera service A/P

---

config/manifests/bases/mariadb-operator.clusterserviceversion.yaml

Also removes deprecated operators.openshift.io/infrastructure-features annotation.
Also, drops the suggested namespace annotation which is not needed.
Jira: https://issues.redhat.com/browse/OSPRH-7939

Add required infrastructure annotations

---

config/rbac/role.yaml
controllers/galera_controller.go
controllers/mariadbaccount_controller.go
controllers/mariadbdatabase_controller.go

We also took the opportunity and added patch to all the existing rbac rules that had update already to avoid similar issues in the future
Resolves: https://issues.redhat.com/browse/OSPRH-8363

Adding patch rbac perm for serviceaccounts

---

api/bases/mariadb.openstack.org_galeras.yaml
api/v1beta1/galera_types.go
config/crd/bases/mariadb.openstack.org_galeras.yaml
controllers/galera_controller.go
pkg/mariadb/statefulset.go
pkg/mariadb/volumes.go
templates/galera/bin/mysql_bootstrap.sh
templates/galera/config/config.json
templates/galera/config/galera.cnf.in
tests/kuttl/tests/galera_log_to_disk/01-assert.yaml
tests/kuttl/tests/galera_log_to_disk/01-deploy_galera.yaml
tests/kuttl/tests/galera_log_to_disk/02-assert.yaml
tests/kuttl/tests/galera_log_to_disk/02-enable_logs.yaml

Add the ability to store galera logs on disk, in addition to logging to stdout.
When used, galera logs on disk, and an additional sidecar container tail the output of the log file on stdout for honouring regular kubectl logs command.
With this change, both the mysql database on disk and the logs use the same PVC, and they each mount a subpath to distinguish database and logs on disk. This way, storage configuration is not impacted, the logs and the database are always collocated, and logs are not stored under /var/log/mysql, so there is no bad interaction with e.g. SST.
By default, logging is not enabled, so there is no operational impact.
Jira: [OSPRH-4983](https://issues.redhat.com//browse/OSPRH-4983)

Ability to configure a Galera CR to log on disk

---

pkg/mariadb/utils.go

right now the pod template specifies these labels and affinity labelSelector.
~~~
template:
metadata:
creationTimestamp: null
labels:
app: galera
cr: galera-openstack-cell1
galera/name: openstack-cell1
galera/namespace: openstack
galera/uid: a14e79ce-ef87-41eb-9e05-ddbaeccb82af
owner: mariadb-operator
spec:
affinity:
podAntiAffinity:
preferredDuringSchedulingIgnoredDuringExecution:
- podAffinityTerm:
labelSelector:
matchExpressions:
- key: service
operator: In
values:
- openstack-cell1-galera
topologyKey: kubernetes.io/hostname
weight: 1
~~~
Which means that the podAntiAffinity would never bump the weight for the galera pods.
This adds a label with the common service selector.
Related: https://issues.redhat.com/browse/OSPRH-8870

Fix labelSelector for podAntiAffinity rule

---

templates/galera/bin/mysql_probe.sh

The liveness probe did not parse non-Primary condition out of the mysql CLI command. Consequently, the liveness did not fail whe a galera node was disconnected from the primary partition and the galera pod could not restart automatically, leading to long delays before restart or sometimes full cluster disruption.
Fix the way probes are handled and refactors bits to allow more precise conditions in startup/readiness/liveness probes.
Jira: [OSPRH-8862](https://issues.redhat.com//browse/OSPRH-8862)

Fix non-Primary checks in liveness probe

---

templates/galera/bin/mysql_wsrep_notify.sh

This change quotes the DB_ROOT_PASSWORD variable used in the mysql_wsrep_notify.sh script to ensure we don't glob or expand potential bash expressions

Quote password to avoid manipulating string

---

controllers/galera_controller.go

When a pod crashes while in the process of starting, the operator cleans up outdated attributes in the galera CR status.
The operator wrongly assumes that it can probe a container's state as soon as it gets a pod object from the API server, which is not always true (e.g when the pod is in "Pending" state).
Fix the attribute clean up by always checking the state of the pod's container before inspecting its container ID.
Jira: [OSPRH-9411](https://issues.redhat.com//browse/OSPRH-9411)

Fix clean up of old attributes when containers are not restarting

---

api/bases/mariadb.openstack.org_galeras.yaml
api/v1beta1/galera_types.go
config/crd/bases/mariadb.openstack.org_galeras.yaml
controllers/galera_controller.go
pkg/mariadb/statefulset.go
pkg/mariadb/volumes.go
templates/galera/bin/detect_last_commit.sh
templates/galera/bin/mysql_shutdown.sh

When a galera cluster is succesfully stopped, the last node to shut down sets a internal flag called "safe_to_bootstrap", that signals that this node should be the one to restart the cluster from.
This can help to improve bootstrap as once this flag is found on a node, there is no need to inspect other nodes. This can also helps to bootstrap a cluster in case e.g. various nodes are unavailable or they suffered a db corruption. As soon as safe_to_bootstrap is read on a node, the cluster can be restarted from it.
Change the way the mariadb operator extracts the sequence number information from galera nodes, to retrieve additional flags such as the "safe_to_bootstrap", and use it to improve the bootstrap node selection.
Note that this requires that the cluster stops in a orchestrated way, …

Fast bootstrap using safe_to_bootstrap flag

---

api/bases/mariadb.openstack.org_galeras.yaml
api/v1beta1/galera_types.go
api/v1beta1/galera_webhook.go
config/crd/bases/mariadb.openstack.org_galeras.yaml
controllers/galera_controller.go

Currently the mariadb operator has webhooks to enforce the galera replica count to be either 1 or 3, which are the two supported deployments on the OpenstackControlPlane.
However there is a need for more flexibility for day two operations, where it can be useful to allow scaling down replicas temporarily to e.g. 2 (for replacement procedure) or even 0 (to temporarily disable database management).
Replace the kubebuilder annotations with minimum and maximum, and let the galera webhook warn about setting replicas to 2 (as it is not advisable to keep that setting for quorum concerns).

Allow intermediate replicas to ease operation

---

api/v1beta1/galera_types.go
api/v1beta1/zz_generated.deepcopy.go
controllers/mariadbaccount_controller.go
controllers/mariadbdatabase_controller.go
pkg/mariadb/account.go
pkg/mariadb/database.go
pkg/mariadb/statefulset.go
tests/kuttl/tests/account_create/01-assert.yaml
tests/kuttl/tests/account_create/01-deploy_galera.yaml
tests/kuttl/tests/account_create/02-assert.yaml
tests/kuttl/tests/account_create/05-assert.yaml

nodeSelectors are not currently applied consistently across all operators.
Some do not support nodeSelectors at all - will be implemented in this series of pull requests.
Some do not apply them to every pod (jobs/cronjobs esp) - will be resolved in this series of pull requests.
Some do not apply a node selector update correctly, only when not initially set.
Some support nodeSelectors but do not inherit the default nodeSelector from the OpenstackControlPlane CR.
Jira: [OSPRH-10734](https://issues.redhat.com//browse/OSPRH-10734)

Ensure nodeSelector logic is consistent for all operators

---

templates/galera/bin/mysql_shutdown.sh
templates/galera/bin/mysql_wsrep_notify.sh

When a galera node is in the process of shutting down (e.g. during a rolling restart caused by a minor update), the node is unable to serve SQL queries, however it is still connected to clients. This confuses clients who get unexpected SQL status [1] and prevent them from retrying their queries, causing unexpected errors down the road.
Improve the pod stop pre-hook to failover the active endpoint to another pod prior to shutting down the galera server, and kill connected clients to force them to reconnect to the new active endpoint. At this stage, the galera server can be safely shutdown as no client will see its WSREP state update.
Also update the failover script: 1) when no endpoint is available, ensure no traffic is going through any pod. 2) do not trigger a endpoint failover as long …

Improve the failover of galera service

---

templates/galera/bin/mysql_shutdown.sh

Update the way the pre-stop hook interacts with the mysql server, to avoid logs showing up in k8s events:
. if no mysql socket is available, do no try to connect.
. do not stop the server in the pre-hook script, this triggers a
failed stop in the k8s events.
. do not call the API server to failover the current endpoint, k8s
removes the stopping pod automatically, and the remaining galera
nodes can elect a new endpoint once the pod is stopping.
. do not call mysqladmin when there are no client connections
Jira: [OSPRH-11392](https://issues.redhat.com//browse/OSPRH-11392)

Improve pre-stop hook to avoid spurious logs

---

pkg/mariadb/const.go
pkg/mariadb/statefulset.go
templates/galera/bin/mysql_probe.sh
templates/galera/config/galera.cnf.in
templates/galera/config/galera_tls.cnf.in

Currently startup probe are scheduled with defaults from k8s (scheduled every 10s, failure threshold of 3). As galera joiner nodes can take a long time to start, this generates unecessary unhealthy events.
Rework how the startup probe work by allowing a single, long probe which internally loops while probe the startup state. Throughout the startup process, keep track of the specific startup phase so in case the startup times out, the probe can log a precise error.
Also rework how joiner nodes are tracked, to fail early in case galera cannot join a primary partition, to avoid the server being stuck until indefinitely until the startup probe times out.
A subsequent commit will provide the ability to override probe settings and timeouts.
Jira: …

Improve tracking and error reporting of startup probe

---

api/go.mod
api/go.sum
api/v1beta1/galera_webhook.go
controllers/galera_controller.go
go.mod
go.sum
pkg/mariadb/statefulset.go

The `resource.MustParse` function was previously used by the operator to process the `storageSize` request provided by the top-level CR. However, even though `defer()` and `recover()` can be used to handle the `panic()` generated by that function in case of a wrong user input, that approach doesn't seem to work properly and the operator crashes without any chance to recover. The `ParseQuantity` implementation returns an error instead of `panic()`, and it can be easily caught at the operator level. This change moves away from `MustParse` usage and relies on the `ParseQuantity` mechanism.
`.SpecCore` webhooks are updated to catch `allErrs` in case of a wrong quantity string is detected, and [1] will push an update with the next lib-common bump.
This has been already fixed in Glance and …

Do not use MustParse to process PVC size

---

controllers/mariadbdatabase_controller.go

In case the DB CR gets recovered/re-created the finalizers from the mariadbdatabases are missing and need to be added manually. This always adds the finalizer if it is missing on the galera.
Jira: https://issues.redhat.com/browse/OSPRH-16507

Always check to add finalizer on galera

---

controllers/galera_controller.go
controllers/mariadbaccount_controller.go
controllers/mariadbdatabase_controller.go

Currently we use deferred call to always update the status field when Reconcile call exits, which seems correct for any other error except Reconciler exits due to panic.
This change adds a call to recover fucntion and try to handle panic and log error.
Closes: [OSPRH-16940](https://issues.redhat.com//browse/OSPRH-16940)

Do not update status when reconciler exits due to panic
